auth:
  issuer: "http://localhost:9000"
  client:
    clientIdExam1: "{bcrypt}$2a$10$qdplIH6LR0hJOb3EmWotBOr3D/1G8qhkF06NMEsNxf7boKarDL176"
    clientIdExam2: "{bcrypt}$2a$10$vY/61rZvKq5GYu6GAUshFeaGWvf5nqnc8Zst5owVYRQsF.PIcyTCC"
